/*
 * util.h
 * Copyright 2009-2010 Paula Stanciu and John Lindgren
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions, and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions, and the following disclaimer in the documentation
 *    provided with the distribution.
 *
 * This software is provided "as is" and without any warranty, express or
 * implied. In no event shall the authors be liable for any damages arising from
 * the use of this software.
 */

#define ID3v1_GENRE_MAX 191
#ifndef TAGUTIL_H
#define TAGUTIL_H

#include <stdint.h>
#include <libfauxdcore/i18n.h>

const char *convert_numericgenre_to_text(int numericgenre);

uint32_t unsyncsafe32 (uint32_t x);
uint32_t syncsafe32 (uint32_t x);

#endif /* TAGUTIL_H */

static const char * const id3v1_genres[ID3v1_GENRE_MAX + 1] = {
      [0] = N_("Blues"),
      [1] = N_("Classic Rock"),
      [2] = N_("Country"),
      [3] = N_("Dance"),
      [4] = N_("Disco"),
      [5] = N_("Funk"),
      [6] = N_("Grunge"),
      [7] = N_("Hip-Hop"),
      [8] = N_("Jazz"),
      [9] = N_("Metal"),
     [10] = N_("New Age"),
     [11] = N_("Oldies"),
     [12] = N_("Other"),
     [13] = N_("Pop"),
     [14] = N_("R&B"),
     [15] = N_("Rap"),
     [16] = N_("Reggae"),
     [17] = N_("Rock"),
     [18] = N_("Techno"),
     [19] = N_("Industrial"),
     [20] = N_("Alternative"),
     [21] = N_("Ska"),
     [22] = N_("Death Metal"),
     [23] = N_("Pranks"),
     [24] = N_("Soundtrack"),
     [25] = N_("Euro-Techno"),
     [26] = N_("Ambient"),
     [27] = N_("Trip-Hop"),
     [28] = N_("Vocal"),
     [29] = N_("Jazz+Funk"),
     [30] = N_("Fusion"),
     [31] = N_("Trance"),
     [32] = N_("Classical"),
     [33] = N_("Instrumental"),
     [34] = N_("Acid"),
     [35] = N_("House"),
     [36] = N_("Game"),
     [37] = N_("Sound Clip"),
     [38] = N_("Gospel"),
     [39] = N_("Noise"),
     [40] = N_("AlternRock"),
     [41] = N_("Bass"),
     [42] = N_("Soul"),
     [43] = N_("Punk"),
     [44] = N_("Space"),
     [45] = N_("Meditative"),
     [46] = N_("Instrumental Pop"),
     [47] = N_("Instrumental Rock"),
     [48] = N_("Ethnic"),
     [49] = N_("Gothic"),
     [50] = N_("Darkwave"),
     [51] = N_("Techno-Industrial"),
     [52] = N_("Electronic"),
     [53] = N_("Pop-Folk"),
     [54] = N_("Eurodance"),
     [55] = N_("Dream"),
     [56] = N_("Southern Rock"),
     [57] = N_("Comedy"),
     [58] = N_("Cult"),
     [59] = N_("Gangsta"),
     [60] = N_("Top 40"),
     [61] = N_("Christian Rap"),
     [62] = N_("Pop/Funk"),
     [63] = N_("Jungle"),
     [64] = N_("Native American"),
     [65] = N_("Cabaret"),
     [66] = N_("New Wave"),
     [67] = N_("Psychedelic"),
     [68] = N_("Rave"),
     [69] = N_("Showtunes"),
     [70] = N_("Trailer"),
     [71] = N_("Lo-Fi"),
     [72] = N_("Tribal"),
     [73] = N_("Acid Punk"),
     [74] = N_("Acid Jazz"),
     [75] = N_("Polka"),
     [76] = N_("Retro"),
     [77] = N_("Musical"),
     [78] = N_("Rock & Roll"),
     [79] = N_("Hard Rock"),
     [80] = N_("Folk"),
     [81] = N_("Folk-Rock"),
     [82] = N_("National Folk"),
     [83] = N_("Swing"),
     [84] = N_("Fast Fusion"),
     [85] = N_("Bebop"),
     [86] = N_("Latin"),
     [87] = N_("Revival"),
     [88] = N_("Celtic"),
     [89] = N_("Bluegrass"),
     [90] = N_("Avantgarde"),
     [91] = N_("Gothic Rock"),
     [92] = N_("Progressive Rock"),
     [93] = N_("Psychedelic Rock"),
     [94] = N_("Symphonic Rock"),
     [95] = N_("Slow Rock"),
     [96] = N_("Big Band"),
     [97] = N_("Chorus"),
     [98] = N_("Easy Listening"),
     [99] = N_("Acoustic"),
    [100] = N_("Humour"),
    [101] = N_("Speech"),
    [102] = N_("Chanson"),
    [103] = N_("Opera"),
    [104] = N_("Chamber Music"),
    [105] = N_("Sonata"),
    [106] = N_("Symphony"),
    [107] = N_("Booty Bass"),
    [108] = N_("Primus"),
    [109] = N_("Porn Groove"),
    [110] = N_("Satire"),
    [111] = N_("Slow Jam"),
    [112] = N_("Club"),
    [113] = N_("Tango"),
    [114] = N_("Samba"),
    [115] = N_("Folklore"),
    [116] = N_("Ballad"),
    [117] = N_("Power Ballad"),
    [118] = N_("Rhythmic Soul"),
    [119] = N_("Freestyle"),
    [120] = N_("Duet"),
    [121] = N_("Punk Rock"),
    [122] = N_("Drum Solo"),
    [123] = N_("A Cappella"),
    [124] = N_("Euro-House"),
    [125] = N_("Dance Hall"),
    [126] = N_("Goa"),
    [127] = N_("Drum & Bass"),
    [128] = N_("Club-House"),
    [129] = N_("Hardcore Techno"),
    [130] = N_("Terror"),
    [131] = N_("Indie"),
    [132] = N_("BritPop"),
    [133] = N_("Negerpunk"),
    [134] = N_("Polsk Punk"),
    [135] = N_("Beat"),
    [136] = N_("Christian Gangsta Rap"),
    [137] = N_("Heavy Metal"),
    [138] = N_("Black Metal"),
    [139] = N_("Crossover"),
    [140] = N_("Contemporary Christian"),
    [141] = N_("Christian Rock"),
    [142] = N_("Merengue"),
    [143] = N_("Salsa"),
    [144] = N_("Thrash Metal"),
    [145] = N_("Anime"),
    [146] = N_("Jpop"),
    [147] = N_("Synthpop"),
    [148] = N_("Abstract"),
    [149] = N_("Art Rock"),
    [150] = N_("Baroque"),
    [151] = N_("Bhangra"),
    [152] = N_("Big Beat"),
    [153] = N_("Breakbeat"),
    [154] = N_("Chillout"),
    [155] = N_("Downtempo"),
    [156] = N_("Dub"),
    [157] = N_("EBM"),
    [158] = N_("Eclectic"),
    [159] = N_("Electro"),
    [160] = N_("Electroclash"),
    [161] = N_("Emo"),
    [162] = N_("Experimental"),
    [163] = N_("Garage"),
    [164] = N_("Global"),
    [165] = N_("IDM"),
    [166] = N_("Illbient"),
    [167] = N_("Industro-Goth"),
    [168] = N_("Jam Band"),
    [169] = N_("Krautrock"),
    [170] = N_("Leftfield"),
    [171] = N_("Lounge"),
    [172] = N_("Math Rock"),
    [173] = N_("New Romantic"),
    [174] = N_("Nu-Breakz"),
    [175] = N_("Post-Punk"),
    [176] = N_("Post-Rock"),
    [177] = N_("Psytrance"),
    [178] = N_("Shoegaze"),
    [179] = N_("Space Rock"),
    [180] = N_("Trop Rock"),
    [181] = N_("World Music"),
    [182] = N_("Neoclassical"),
    [183] = N_("Audiobook"),
    [184] = N_("Audio Theatre"),
    [185] = N_("Neue Deutsche Welle"),
    [186] = N_("Podcast"),
    [187] = N_("Indie Rock"),
    [188] = N_("G-Funk"),
    [189] = N_("Dubstep"),
    [190] = N_("Garage Rock"),
    [191] = N_("Psybient")
};
